# Generated by Django 4.0.6 on 2022-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pub', 'Publish'), ('drf', 'Draft')], max_length=3),
        ),
    ]
